version: '3.7'

services:
  flask_app:
    build:
      context: .  # Ensure it points to your Flask project directory
      dockerfile: Dockerfile.app  # Update this if you have a custom Dockerfile for Flask
    container_name: flask_app
    ports:
      - "8000:8000"  # Adjust port if needed
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # Set MLflow URI
    depends_on:
      - mlflow
    networks:
      - mynetwork

  mlflow:
    image: mlflow:latest  # You can specify your version if needed
    container_name: mlflow
    ports:
      - "5000:5000"  # Adjust MLflow port if needed
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # Make sure MLflow can track the URI
    networks:
      - mynetwork
    volumes:
      - mlflow_data:/mlruns  # Persist MLflow data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      retries: 5

networks:
  mynetwork:
    driver: bridge

volumes:
  mlflow_data:  # Volume for persisting MLflow data
