name: Docker Image CI

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the job that will run the build
jobs:
  build:
    # This specifies the runner environment (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 3: Log in to Docker Hub (use secrets to keep credentials safe)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mariem773/mariem_nasri_4ds4_mlops:latest
